((magit-commit nil)
 (magit-dispatch nil)
 (magit-fetch nil)
 (magit-gitignore nil)
 (magit-log
  ("-n256" "--graph" "--decorate")
  ("-n256" "--decorate"))
 (magit-merge nil)
 (magit-pull nil)
 (magit-push nil)
 (my/buffer-command nil)
 (my/file-command nil)
 (my/project-command nil))
